### ISSUE TITLE
Class names based on lower case localized_name?

### ISSUE THREAD

**Issue by ntucker** [bontscho/dota2-minimap-hero-sprites#2]
Hi, zuus is a very strange name. It would be nice if the localized_name field from the steam api could be used to create classnames. Thanks!

**Comment by bontscho** [comment]
https://github.com/bontscho/dota2-minimap-hero-sprites/commit/aeb54466ee50b27e48f69aed5f4acfe4a58cef98

probably a bit, but nevertheless :sweat_smile:
