### ISSUE TITLE
Add Hoodwink

### ISSUE THREAD

**Issue by RoccoFarrell** [bontscho/dota2-minimap-hero-sprites#22]
Hoodwink icon missing since she was added after the last update

**Comment by bontscho** [comment]
thanks for the notice, currently i don't have dota and the tools installed and i can't really tell when i have the time to get around to it.
a pr would be greatly appreciated :)

**Comment by RoccoFarrell** [comment]
PR submitted :) Let me know if I ran everything correctly!

**Comment by bontscho** [comment]
thank you very much 🍻 !

v2.4.0 is out

#23
