### ISSUE TITLE
Faceless Void update?

### ISSUE THREAD

**Issue by xhila** [bontscho/dota2-minimap-hero-sprites#4]
Since I'm on mac and I can't open the VPK, I wanted to update the Faceless Void to the new sprite. Seen here: http://hydra-media.cursecdn.com/dota2.gamepedia.com/7/73/Faceless_Void_icon.png?version=54dd9fa11c6db1ba7d8d64da4d401f83, Let me know if it's ok

**Comment by bontscho** [comment]
https://github.com/bontscho/dota2-minimap-hero-sprites/pull/5
