### ISSUE TITLE
Not really an issue but I would thank you if ...

### ISSUE THREAD

**Issue by KnorrAlex** [bontscho/dota2-minimap-hero-sprites#9]
Hey bontscho,

I am sorry for getting in touch with you this way but Github removed the private chat sooo .... yeah.

I would like to ask you some short questions about your Dota2Timer Overwolf app. 
If you could write me an e-mail (a.knorr2206@gmail.com) I would thank you so much.

Sincerly 
Alex Knorr

PS: Or look me up on Gitter, you can also join my chatroom ([Join here](https://gitter.im/KnorrAlexChat/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link))

**Comment by bontscho** [comment]
the overwolf app is no longer maintained
